### PR TITLE
Make configs less bulky

### PR DESCRIPTION
**Pull request by Jaywalker**
In an effort to make my talkkonnect config less bulky, I have added some sensible autodetecting of paths for the soundfiles.

If no filenameandpath is provided for a sound file, talkkonnect will now search in either ../share/, the executable's directory, or the $GOPATH/src/github.com/talkkonnect/talkkonnect directory for the sound files.

Config file now expected to live in $HOME/.config/talkkonnect/talkkonnect.xml by default, but also searches in the executable's directory.

Also added better pulseaudio support (see also my volume-go PR), added some extra debugging information where I found it helpful, and made some names more consistent.

### CODE REVIEW

**Comment by talkkonnect** [comment]
Jaywalker, 
thank you so much for your help and interest in talkkonnect. It makes me very excited that someone else is also interested in talkkonnect. I will have a look and study your changes and commit them for the betterment of talkkonnect.

thanks again!

**Comment by talkkonnect** [comment]
I have made the changes you commented and they are released in version 1.46.39 released 14/02/2020.

thank you for your comments and help, much appreciated!

**Comment by Jaywalker** [comment]
Happy to help, and I have more coming. Any particular reason you chose to manually remake my commits rather than just a regular `git merge`? I only ask because it makes things more difficult for me to track upstream in my fork for my future pull requests if you plan to keep doing it that way.

**Comment by talkkonnect** [comment]
Thank you for your continued help much appreciated. The reason I did not use git merge is I am self taught and have not learned git properly. So when I was presented with 3 different ways of merging options, I got confused and wanted to merge your code ASAP so I did it manually. For you next git merge request I will ask your advise which option to choose and how to do it. I appreciate your contributions and would like to make it easier for all to contribute. I have been programming on talkkonnect solo since the beginning so have not learned the proper way to work with git in a group environment.

**Pull request closed without merging**
